### ISSUE TITLE
9.py

### ISSUE THREAD

**Issue by sakethvishnu059** [deephunt3r/l#1]
def knapSack(w, wt, val, n):
    K = [[0 for x in range( w+ 1)] for x in range(n + 1)]
    for i in range(1,n + 1):
        for w in range(1,w + 1):

            if wt[i-1] <= w:
                K[i][w] = max(val[i] + K[i-1][w-wt[i]], K[i-1][w])
            else:
                K[i][w] = K[i-1][w]
    print("The maximum profit is :",k[n][w])
    p = k[n][w]
    bag = []
    for j in range(i-1,-1,-1):
        if p in k[j]:
            continue
        else:
            bag.append(j+1)
            p -= val[j]
    print("The objects in the bag are : ",bag)

val=list(map(int,input("Enter the values: ").split()))
wt=list(map(int,input("Enter the weights:").split()))
w=int(input("Enter the maximum capacity:"))
n=len(wt)
knapSack(w, wt, val, n)

**Comment by rakesh0x7** [comment]
Thanks for your contribution 🎉
